version: '3'

services:
  riemann:
    image: rhomewood/riemann
    #build:
      #context: .
      #dockerfile: Dockerfile
    networks:
      - monitoring
    ports:
      - '5555:5555/tcp'
      - '5555:5555/udp'
      - '5556:5556'
    volumes:
      - ./riemann/data/etc:/app/etc
  
  graphite:
    image: sitespeedio/graphite
    networks:
      monitoring:
        aliases:
          - database
    ports:
      - "8080:80"
      - "2003:2003"
    volumes:
      - ./graphite/data/htpass/.htpasswd:/etc/nginx/.htpasswd
      - ./graphite/data/whisper:/opt/graphite/storage/whisper
      - ./graphite/data/logrotate.d:/etc/logrotate.d
      - ./graphite/data/log:/var/log

  grafana:
    image: monitoringartist/grafana-xxl
    environment:
      GRAFANA_VERSION: "4.4.1"
    networks:
      monitoring:
        aliases:
          - display
    ports:
      - "3000:3000"
    volumes:
      - grafana-plugins:/grafana-plugins
      - ./grafana/data:/var/lib/grafana
      - ./grafana/logs:/var/log/grafana
      - ./grafana/config:/etc/grafana

networks:
  monitoring:

volumes:
  grafana-plugins: